spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_DB/ReciPT
    username: sa
    password:
    driver-class-name: org.h2.Driver

    # 이미지 용량 설정
    servlet:
      multipart:
        maxFileSize: 10MB
        maxRequestSize: 20MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true      -> System.out
        format_sql: true
        use_sql_comments: true #실행되는 JPQL 보기

  data:
    web:
      pageable:
        default-page-size: 10 #기본 page 사이즈(Web 확장)
        max-page-size: 2000 #최대 page 사이즈(Web 확장)

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace      # 파라미터까지 볼 수 있음

